use_frameworks!

platform :ios, '8.0'

target 'XWFoundationExtension_Example' do
  pod 'XWFoundationExtension', :path => '../'

  target 'XWFoundationExtension_Tests' do
    inherit! :search_paths

    
  end
end
